name: Question Report
title: Report - <Short description>
description: "Report of question content (invalid, incorrect, etc.)"
labels: ["question", "report", "good first issue"]
body:
  - type: markdown
    attributes:
      value: "## Thanks for taking the time to fill out this question report!"
  - type: input
    id: reference
    attributes:
      label: Question Reference
      description: Paste the copied reference of the question
      placeholder: Question reference
    validations:
      required: true
  - type: radio
    id: reason
    attributes:
      label: "Why you're filling this report?"
      description: Select one option
      options:
        - label: The question is incorrect
        - label: The question is outdated
        - label: The question is not part of the exam content
        - label: Other
    validations:
      required: true
  - type: textarea
    id: explain
    attributes:
      label: "Please, provide a brief explanation for why you checked the option above:"
    validations:
      required: true
    
    
