name: Update contributors graph

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'contributors/**'

jobs:
  run-my-action:
    runs-on: windows-latest
    name: Update contributors graph
    permissions:
      contents: write
    steps:
      - uses: salgado2004/contributors-chart-action@v1.0.0-beta
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          include-bots: false